import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Todo app",
    description: "Generated by create next app",
    keywords: "alo, new, next13",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className} style={{ position: "relative", margin: 0, padding: 0 }}>
                <div style={{ position: "absolute", top: 0, left: 0, width: "150px", height: "100vh", background: "red" }}>Layout Root</div>
                <div style={{ marginLeft: "150px" }}>{children}</div>
            </body>
        </html>
    );
}
